env:
    credentials: "ENCRYPTED[!fea520524bfb71d31b482938c38fa0d787cee768268714868aefaf7fde9fcbc3f41f3cf162c3a300824e72f0d91f305b!]"
    rcloneconfig: "ENCRYPTED[!3fcfaacb0ece8f18ef8a4db77414d486b6634380ea88e7fc1988a6ebfe7d7504b32e24ffdfaaeb586329f1cd9b5c6585!]"
    tokentl: "ENCRYPTED[!7ed7ff711b889fd954c71e98a2d4bcbc50aa099688a626a83da794e7aa4afd58557752b1b614dd3631c31f6b655a346c!]"
    idtl: "ENCRYPTED[!d89cd5c6cdc21a2eba483db66c48545c510fcfe378fd3a9f6033f59695321d03a21bb863eb48ad36d2543201324343f5!]"
    lunch : lunch havoc_juice-user
    make: make bacon
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "Rahmad Adi Pratama"
       - git config --global user.email "OhMyVenyx@proton.me"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy venyx:havoc-11/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh
  
  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - mkdir -p ~/.anu
      - export PATH="${HOME}/.anu:${PATH}"
      - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.anu/repo
      - chmod a+rx ~/.anu/repo
      - rm -rf ~/rom
      - mkdir -p ~/rom
      - cd ~/rom
      - rm -rf * .repo
      - git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/HavocOS-Revived/android_manifest -b eleven -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - git clone --depth 1 https://github.com/lynnnnzx/android_device_xiaomi_juice-r -b havoc device/xiaomi/juice
      - git clone --depth 1 https://github.com/lynnnnzx/vendor_xiaomi_juice vendor/xiaomi/juice
      - git clone --depth 1 https://github.com/IDN-Labs/kernel_juice kernel/xiaomi/juice
      - git clone --depth 1 https://github.com/lynnnnzx/platform_packages_inputmethods_Gboard packages/inputmethods/Gboard
      - git clone --depth 1 https://gitlab.com/OhMyVenyx/clang-r450784e prebuilts/clang/host/linux-x86/clang-mistyx
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="venyx"
      - export BUILD_HOSTNAME="IDN-Labs"
      - export HAVOC_BUILD_TYPE="Private"
      - sed -i 's|-u ||g' ~/rom/vendor/havoc/config/version.mk
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz venyx:havoc-11 -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"
